### ISSUE TITLE
How many data is used for training/evaluation/testing?

### ISSUE THREAD

**Issue by siyuan2018** [BoyuanChen/boombox#1]
Very impressive work! 

Maybe I miss the part, but how many data is used for training/evaluation/testing?

**Comment by BoyuanChen** [comment]
Thanks for your interests!

We provide the exact splits for each random seed in our data.zip file (download link in the README). Inside each shape folder, the splits are in files named as data_split_dict_{random_seed}.json, Roughly speaking, there are a little more than 1500 data points. The splits is 80/10/10 for train/val/test.
